extends Node
#初始道具栏
var csdaojvlan = [
	[7,{"daojvname":"zb-toukui0","daojvshuliang":1 ,"fy":6,"sm":13}],
	[8,{"daojvname":"zb-shenti0","daojvshuliang":1 ,"fy":19}],
	[9,{"daojvname":"zb-wuqi0","daojvshuliang":1 ,"gj":13}],
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null
	]
#道具栏
var daojvlan = [
	[7,{"daojvname":"zb-toukui0","daojvshuliang":1 }],
	[8,{"daojvname":"zb-shenti0","daojvshuliang":1 }],
	[9,{"daojvname":"zb-wuqi0","daojvshuliang":1 }],
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null,
	null
	]
#装备栏
var zhuangbeilan = [
	[8,{"daojvname":"zb-tukui2","daojvshuliang":1 }],
	[9,{"daojvname":"zb-shenti1","daojvshuliang":1 }],
	null,
	null
	]
#物品库
var wupinku = [
	[1,{"daojvname":"chick",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/chick_gaitubao_66x65.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"我是一只鸡",
	"hebing":true,
	"daojvxvhao":"1"
	}],
	[2,{"daojvname":"bear",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/bear_gaitubao_66x66.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"我是熊，我是熊",
	"hebing":true,
	"daojvxvhao":"2"
	}],
	[3,{"daojvname":"xiaochick",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/chicken_gaitubao_66x66.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"我是一只小鸡",
	"hebing":true,
	"daojvxvhao":"3"
	}],
	[4,{"daojvname":"buff",
	"daojvshuliang":1,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/buffalo_gaitubao_66x66.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"我是一个怪物",
	"hebing":true,
	"daojvxvhao":"4"
	}],
	[5,{"daojvname":"croco",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/crocodile_gaitubao_66x65.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"我是一只青蛙啊",
	"hebing":true,
	"daojvxvhao":"5"
	}],
	[6,{"daojvname":"cow",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/cow_gaitubao_66x65.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"牛逼",
	"hebing":true,
	"daojvxvhao":"6"
	}],
	[7,{"daojvname":"zb-toukui0",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/HELMS_01.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"头盔0级\r\n提供防御和生命",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":0,
	"fy":6,
	"sm":13
	}],
	[8,{"daojvname":"zb-toukui10",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/HELMS_02.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"头盔10级\r\n提供防御和生命",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":0,
	"fy":13,
	"sm":40
	}],
	[9,{"daojvname":"zb-toukui20",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/HELMS_03.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"头盔20级\r\n提供防御和生命",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":0,
	"fy":20,
	"sm":68
	}],
	[8,{"daojvname":"zb-toukui30",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/HELMS_04.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"头盔30级\r\n提供防御和生命",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":0,
	"fy":27,
	"sm":95
	}],
	[8,{"daojvname":"zb-toukui40",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/HELMS_05.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"头盔40级\r\n提供防御和生命",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":0,
	"fy":33,
	"sm":122
	}],
	[8,{"daojvname":"zb-toukui50",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/HELMS_06.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"头盔50级\r\n提供防御和生命",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":0,
	"fy":40,
	"sm":150
	}],
	[7,{"daojvname":"zb-shenti0",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/CHESTS_01.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"身体0级\r\n提供强大的防御",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":0,
	"fy":19,
	"sm":0
	}],
	[8,{"daojvname":"zb-shenti10",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/CHESTS_02.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"身体10级\r\n提供强大的防御",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":0,
	"fy":46,
	"sm":0
	}],
	[9,{"daojvname":"zb-shenti20",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/CHESTS_03.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"身体20级\r\n提供强大的防御",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":0,
	"fy":73,
	"sm":0
	}],
	[8,{"daojvname":"zb-shenti30",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/CHESTS_04.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"身体30级\r\n提供强大的防御",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":0,
	"fy":101,
	"sm":0
	}],
	[8,{"daojvname":"zb-shenti40",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/CHESTS_05.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"身体40级\r\n提供强大的防御",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":0,
	"fy":128,
	"sm":0
	}],
	[8,{"daojvname":"zb-shenti50",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/CHESTS_06.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"身体50级\r\n提供强大的防御",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":0,
	"fy":155,
	"sm":0
	}],
	[7,{"daojvname":"zb-wuqi0",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/DAGGERS_05.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"武器0级\r\n提供强大的攻击",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":13
	}],
	[8,{"daojvname":"zb-wuqi10",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/DAGGERS_06.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"武器10级\r\n提供强大的攻击",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":54
	}],
	[9,{"daojvname":"zb-wuqi20",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/DAGGERS_07.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"武器20级\r\n提供强大的攻击",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":95
	}],
	[8,{"daojvname":"zb-wuqi30",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/DAGGERS_08.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"武器30级\r\n提供强大的攻击",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":136
	}],
	[8,{"daojvname":"zb-wuqi40",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/DAGGERS_09.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"武器40级\r\n提供强大的攻击",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":177
	}],
	[8,{"daojvname":"zb-wuqi50",
	"daojvshuliang":1 ,
	"daojvtubiao":preload("res://daojvxitong/daojvtupian/DAGGERS_10.png"),
	#"daojvxiaoguo":Zhujueshuxing.add_hp(10),
	"daojvmiaoshu":"武器50级\r\n提供强大的攻击",
	"hebing":true,
	"daojvxvhao":"7",
	"gj":218
	}],


]
